# Generated by Django 2.1.5 on 2019-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pubgusername',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
