# Generated by Django 2.1.5 on 2019-01-12 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('participants', models.IntegerField(blank=True, default=0)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('reg_fee', models.IntegerField(blank=True, default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('team_type', models.CharField(blank=True, max_length=50)),
                ('prize_pool', models.IntegerField(blank=True, default=0)),
                ('per_kill', models.IntegerField(blank=True, default=0)),
                ('map', models.CharField(choices=[('Erangal', 'Erangal'), ('Miramar ', 'Miramar '), ('Sanhok', 'Sanhok'), ('Vikendi', 'Vikendi')], default='Erangal', max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
