# Generated by Django 2.1.5 on 2019-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='match_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
