# Generated by Django 2.1.5 on 2019-01-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Platform',
        ),
        migrations.RemoveField(
            model_name='post',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reg_fee',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_type',
        ),
        migrations.AddField(
            model_name='post',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
