# Generated by Django 2.1.5 on 2019-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190109_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='Platform',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='birth_date',
            new_name='starts_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bio',
        ),
        migrations.AddField(
            model_name='post',
            name='team_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
