# Generated by Django 2.1.5 on 2019-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190112_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
