# Generated by Django 2.1.5 on 2019-01-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190109_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reg_fee',
            field=models.IntegerField(blank=True, default=0, max_length=30),
        ),
    ]
