# Generated by Django 2.1.5 on 2019-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190112_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='match_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
