# Generated by Django 2.1.5 on 2019-01-16 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190116_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_kill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 23, 33, 11, 810213)),
        ),
    ]
