# Generated by Django 2.1.5 on 2019-01-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_reg_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='reg_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
