# Generated by Django 2.1.5 on 2019-02-10 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190124_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='moreinfo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 12, 17, 44, 35932)),
        ),
    ]
