# Generated by Django 2.1.5 on 2019-01-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.IntegerField(blank=True, default=0, max_length=100),
        ),
    ]
