# Generated by Django 2.1.5 on 2019-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190112_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
