# Generated by Django 2.1.5 on 2019-01-17 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190116_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prize_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 15, 26, 7, 969531)),
        ),
    ]
