# Generated by Django 2.1.5 on 2019-01-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190112_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='match_id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
