# Generated by Django 2.1.5 on 2019-01-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190117_2104'),
        ('blog', '0007_auto_20190117_2147'),
    ]

    operations = [
    ]
