# Generated by Django 2.1.5 on 2019-01-18 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_merge_20190118_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='room_pass',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 14, 59, 53, 62059)),
        ),
    ]
