# Generated by Django 2.1.5 on 2019-01-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190114_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='srank_2',
            new_name='rank_2',
        ),
    ]
