# Generated by Django 2.1.5 on 2019-01-18 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190118_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room_pass',
        ),
        migrations.AddField(
            model_name='post',
            name='room_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='room_pass',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 23, 46, 32, 602574)),
        ),
    ]
