# Generated by Django 2.1.5 on 2019-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_auto_20190113_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.TextField(verbose_name='TXN ID'),
        ),
    ]
